version: '3'
services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - rabbitmq-service
      - mongodb
      - billing
      - auth
    volumes:
      - .:/usr/src/app
      - orders-node-modules:/usr/src/app/node_modules
    ports:
      - 9900:9900
  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - rabbitmq-service
      - mongodb
      - auth
    volumes:
      - .:/usr/src/app
      - billing-node-modules:/usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 9901:9901
    depends_on:
      - rabbitmq-service
      - mongodb
    volumes:
      - .:/usr/src/app
      - auth-node-modules:/usr/src/app/node_modules

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
volumes:
  auth-node-modules:
  orders-node-modules:
  billing-node-modules:
  rabbit-mq-data:
